# Generated by Django 4.2.4 on 2023-11-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_owner_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='owner_comment',
        ),
    ]
